sudo: required
services:
  - docker

before_install:
  - dockerbuild -t prodiptasengupta/docker-react -f Dockerfile.dev Dockerfile.dev .

script:
  - docker run -e CI=true prodiptasengupta/docker-react npm run test -- --coverage